import Foundation

/// Action type that can be executed directly from AI recommendations or chat
public enum AIActionType: String, Codable, Sendable, Equatable {
    case purgeRAM = "purgeRAM"
    case scanJunk = "scanJunk"
    case cleanJunk = "cleanJunk"
    case checkUpdates = "checkUpdates"
    case flushDNS = "flushDNS"
    case resetQuickLook = "resetQuickLook"
    case killProcess = "killProcess"
    
    public var iconName: String {
        switch self {
        case .purgeRAM: return "memorychip.fill"
        case .scanJunk: return "sparkles.square.filled.on.square"
        case .cleanJunk: return "trash.fill"
        case .checkUpdates: return "arrow.triangle.2.circlepath"
        case .flushDNS: return "network"
        case .resetQuickLook: return "eye.fill"
        case .killProcess: return "xmark.octagon.fill"
        }
    }
}

/// Actionable button embedded in AI responses
public struct AIAction: Identifiable, Codable, Sendable, Equatable {
    public let id: UUID
    public let title: String
    public let type: AIActionType
    public let targetPID: Int32?
    public let targetPath: String?
    
    public init(id: UUID = UUID(), title: String, type: AIActionType, targetPID: Int32? = nil, targetPath: String? = nil) {
        self.id = id
        self.title = title
        self.type = type
        self.targetPID = targetPID
        self.targetPath = targetPath
    }
}

/// Diagnostic Insight generated by NVIDIA NIM or Local Heuristic AI Engine
public struct AIInsight: Identifiable, Codable, Sendable, Equatable {
    public let id: UUID
    public let title: String
    public let summary: String
    public let severity: Severity
    public let category: String
    public let actions: [AIAction]
    public let timestamp: Date
    
    public enum Severity: String, Codable, Sendable, Equatable {
        case info = "Bilgi"
        case warning = "Uyarı"
        case critical = "Kritik"
        case recommendation = "Tavsiye"
        
        public var colorName: String {
            switch self {
            case .info: return "blue"
            case .warning: return "orange"
            case .critical: return "red"
            case .recommendation: return "green"
            }
        }
        
        public var iconName: String {
            switch self {
            case .info: return "info.circle.fill"
            case .warning: return "exclamationmark.triangle.fill"
            case .critical: return "flame.fill"
            case .recommendation: return "lightbulb.fill"
            }
        }
    }
    
    public init(
        id: UUID = UUID(),
        title: String,
        summary: String,
        severity: Severity,
        category: String = "Sistem",
        actions: [AIAction] = [],
        timestamp: Date = Date()
    ) {
        self.id = id
        self.title = title
        self.summary = summary
        self.severity = severity
        self.category = category
        self.actions = actions
        self.timestamp = timestamp
    }
}

/// Interactive Chat message between User and AI Copilot
public struct AIChatMessage: Identifiable, Codable, Sendable, Equatable {
    public let id: UUID
    public let role: Role
    public var content: String
    public let timestamp: Date
    public var actions: [AIAction]
    public var isThinking: Bool
    
    public enum Role: String, Codable, Sendable, Equatable {
        case user = "user"
        case assistant = "assistant"
        case system = "system"
    }
    
    public init(
        id: UUID = UUID(),
        role: Role,
        content: String,
        timestamp: Date = Date(),
        actions: [AIAction] = [],
        isThinking: Bool = false
    ) {
        self.id = id
        self.role = role
        self.content = content
        self.timestamp = timestamp
        self.actions = actions
        self.isThinking = isThinking
    }
}
